### ISSUE TITLE
Missing version 0.1.2

### ISSUE THREAD

**Issue by samuelburnham** [supranational/semolina#1] opened 2022-11-21 21:58 UTC
The latest published version on [crates.io](url) (0.1.2) doesn't match the one here (0.1.1). This crate builds fine when cloned from Github, but when imported from crates into [pasta-msm](https://github.com/supranational/pasta-msm/blob/main/Cargo.toml#L31), a Github clone of the latter gives the following warning:

```
warning: In file included from /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/semolina-0.1.2/src/pasta_t.hpp:13,
warning:                  from /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/sppark-0.1.2/sppark/ff/pasta.hpp:47,
warning:                  from src/pippenger.cpp:8:
warning: /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/semolina-0.1.2/src/bytes.h:112:13: warning: ‘void bytes_from_hexascii(unsigned char*, size_t, const char*)’ defined but not used [-Wunused-function]
warning:   112 | static void bytes_from_hexascii(unsigned char *ret, size_t sz, const char *hex)
warning:       |             ^~~~~~~~~~~~~~~~~~~
warning: cc1plus: note: unrecognized command-line option ‘-Wno-unused-command-line-argument’ may have been intended to silence earlier diagnostics
```

Happy to move the issue to `pasta-msm` instead.

**Comment by dot-asm** [comment] 2022-11-25 16:31
While there indeed is a version mismatch(*), I can't reproduce the warning. Not that I can't imagine why it complains, I fail to imagine/figure out that it has everything to do with the said version mismatch. What's your `gcc --version`? Are you compiling with CC environment variable set? In which case, what's your `$CC --version`?

(*) Apparently `cargo publish` doesn't check for this kind of inconsistency, will fix.

**Comment by dot-asm** [comment] 2022-11-25 17:04
> what's your `$CC --version`?

Just in case, it would be mostly for the reference purposes. So if you don't have time, don't feel obligated to rush providing the information. The warning will be resolved with or without the feedback :-)

**Comment by samuelburnham** [comment] 2023-01-21 00:25
Apologies for the delayed response, here's my info for NixOS (also tested with Ubuntu without setting `$CC`):
- `gcc --version` = `gcc 11.3.0`
- `$CC --version` = `gcc 11.3.0`
- `ld --version` = `GNU ld 2.38`

**Comment by dot-asm** [comment] 2023-01-24 16:27
Thanks!

**Comment by leonardoalt** [comment] 2023-05-14 15:30
Hi, I'm running into a similar thing. `semolina` itself compiles fine when I clone it, but both `lurk-lab/pasta-msm` and `supranational/pasta-msm` current `main` fail with https://gist.github.com/leonardoalt/79f2984dcd6cead9942deebba1334e22. I don't really know why or how this is happening.

**Comment by dot-asm** [comment] 2023-05-17 10:06
> I'm running into a similar thing.

But not the same :-) The original was a warning, not a failure, but both are fixed now. Well, the warning was resolved earlier...

**Closed as completed by dot-asm** 2023-05-17 10:06 UTC
